name: Run Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: admin_user
          POSTGRES_PASSWORD: admin_pass
          POSTGRES_DB: mytasksproapp
        ports: ["5432:5432"]
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:                         # <--- Add your env var here (at the job level)
      DATABASE_URL: postgresql://admin_user:admin_pass@localhost:5432/mytasksproapp

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Wait for Postgres to be ready
        run: |
          for i in {1..10}; do
            pg_isready -h localhost -p 5432 && break
            echo "Waiting for Postgres..."
            sleep 2
          done
      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$PWD" >> $GITHUB_ENV
      - name: Run tests
        run: pytest
        env:                   # <--- Also safe to add env var here if not at job level
          DATABASE_URL: postgresql://admin_user:admin_pass@localhost:5432/mytasksproapp
